spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.60.8:3306/hetao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: jxproduct
    password: prol9(7)8ihjrt
    max-active: 10
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    validationQuery: SELECT 'x'
    connectionInitSqls: set names utf8mb4
