server:
  port: 9090
spring:
  profiles:
    include: dev_jdbc
  application:
    name: hetao-service
  cloud:
   nacos:
    discovery:
     server-addr: 172.20.60.57:8848
mybatis:
  type-aliases-package: com.baxianguohai.hetaodamai.biz.dao
  mapper-locations: classpath:mapper/*.xml

logging:
  level.root: info
  level.com.baxianguohai: info
